framework:
    secret: '%env(APP_SECRET)%'
    session: true
    form:
        csrf_protection:
            enabled: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
