
services:
  database:
    image: mysql:8.0
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
