services:
  app:
    build:
      context: .
    depends_on:
      - database
  database:
    image: mysql:9.2
    env_file:
      - .env.prod
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - parraindex-data:/var/lib/mysql
