liip_imagine:
    twig:
        mode: lazy
    driver: gd
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'
    filter_sets:
        avatar_thumb:
            quality: 85
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                strip:
                    ~
        avatar_full:
            quality: 90
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: inset
                strip:
                    ~
