vich_uploader:
    db_driver: orm
    mappings:
        person_avatar:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options:
                    algorithm: sha256
                    length: 40
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false
