<?php

declare(strict_types=1);

namespace App\Api;

enum ErrorCode: string
{
    case PERSON_NOT_FOUND     = 'PERSON_NOT_FOUND';
    case SPONSOR_NOT_FOUND    = 'SPONSOR_NOT_FOUND';
    case CONTACT_NOT_FOUND    = 'CONTACT_NOT_FOUND';
    case USER_NOT_FOUND       = 'USER_NOT_FOUND';
    case INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT';
    case PERSON_ALREADY_HAS_ACCOUNT = 'PERSON_ALREADY_HAS_ACCOUNT';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';
    case UNAUTHORIZED     = 'UNAUTHORIZED';
    case FORBIDDEN        = 'FORBIDDEN';
    case INTERNAL_ERROR   = 'INTERNAL_ERROR';
}
